### ISSUE TITLE
No Dragons

### ISSUE THREAD

**Issue by gr3atest** [aschlorke/CppGameProgrammingTutorial#1]
I couldn't find dragons. Help plz game no work

**Comment by aschlorke** [comment]
Closing issue, all u need is Monke

**Comment by gr3atest** [comment]
Hahah this is Abdullah, your long lost buddy. Can we reconnect somehow?

**Comment by aschlorke** [comment]
Haha hey man! Idk a better way, you can email me at aschlorke@yahoo.com and I can give you my number there.
